### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by Lange** [jay0lee/chrome-bisect#1]
Hi there! Just wanted to say thank you for this, it's exactly what I wanted and is making my debugging process so much easier.

Thanks! 🎉

**Comment by jay0lee** [comment]
Glad to hear it. Can you tell me more about how you're using it?

**Comment by Lange** [comment]
I have a codebase I come back to every 6 months for a specific twice-annual event. Unfortunately, Chrome has often broken things in that downtime. I've been using this tool to help me file concise, accurate crbugs about these regressions.

Here's the current one I'm working on: https://bugs.chromium.org/p/chromium/issues/detail?id=670292

**Comment by jay0lee** [comment]
Excellent, glad to hear about it.
